runtime: nodejs20

env_variables:
  NODE_ENV: production

automatic_scaling:
  max_instances: 10
  min_instances: 0

handlers:
  - url: /sitemap.xml
    static_files: dist/portfolio-app/browser/sitemap.xml
    upload: dist/portfolio-app/browser/sitemap.xml
  - url: /(.*\..*)
    static_files: dist/portfolio-app/browser/\1
    upload: dist/portfolio-app/browser/(.*\..*)
  - url: /.*
    static_files: dist/portfolio-app/browser/index.html
    upload: dist/portfolio-app/browser/index.html
